### ISSUE TITLE
关于习惯问题

### ISSUE THREAD

**Issue by luoxiao** [chvin/react-tetris#19]
你好，做得很棒，所以闲暇时候也会经常玩玩。
可有个体验感受说下哦，这不是我们童年接机的手势习惯，我们童年的都是 左边方向键，右边圆圈变形键。我上传了一张小时接机图模型，希望作者有空能调整一下哦....谢谢。期待~
![image](https://user-images.githubusercontent.com/4163258/43368407-10702c3c-938f-11e8-8a11-5b8311118d7b.png)

**Comment by chvin** [comment]
嗯，有空调整下..

**Comment by pinuofeng** [comment]
@chvin 大牛   佩服。。。
