### ISSUE TITLE
iOS12, Safari compatibility issue

### ISSUE THREAD

**Issue by wsy** [chvin/react-tetris#24]
iOS12下，Safari里，快速点击某个按钮（比如连按两下“向左”按钮），会触发页面缩放操作。

Under iOS12, using Safari, when click same button rapidly (e.g. Press "Move Left" button twice quickly), will trigger the zoom operation of the browser.

**Comment by includenaneve** [comment]
666

**Comment by zhouyiqin** [comment]
> iOS12下，Safari里，快速点击某个按钮（比如连按两下“向左”按钮），会触发页面缩放操作。
> 
> Under iOS12, using Safari, when click same button rapidly (e.g. Press "Move Left" button twice quickly), will trigger the zoom operation of the browser.

谢谢你的提醒，已经修复了哈

**Comment by chvin** [comment]
> iOS12下，Safari里，快速点击某个按钮（比如连按两下“向左”按钮），会触发页面缩放操作。
> 
> Under iOS12, using Safari, when click same button rapidly (e.g. Press "Move Left" button twice quickly), will trigger the zoom operation of the browser.

谢谢你的提醒，已经修复了哈

**Comment by wsy** [comment]
其实那天还有个Bug，忘开Issue了。

**Comment by chvin** [comment]
啥bug？
