### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by eladcandroid** [chvin/react-tetris#3]

**Comment by chvin** [comment]
You can read [README-EN](https://github.com/chvin/react-tetris/blob/master/README-EN.md).

**Comment by eladcandroid** [comment]
It's 404..

**Comment by chvin** [comment]
really?
https://github.com/chvin/react-tetris/blob/master/README-EN.md
I can visit..

**Comment by eladcandroid** [comment]
The second link works. Thanks!
