### ISSUE TITLE
请求上架到AppStore

### ISSUE THREAD

**Issue by xaoxuu** [chvin/react-tetris#34]
作者你好，您这个项目太完美了，我想上架到AppStore可以吗？

我有苹果的开发者账号，想写一个简单的App，在App内用浏览器加载 `https://chvin.github.io/react-tetris` 这个页面。

1. 会注明作者
2. 不插入广告
3. 免费

**Comment by 2826418736** [comment]
您好，
非常感谢您给我发来的邮件，但是我并不是这个项目的作者，这仅是一个我收藏的项目。
如果您真的想去完善这个项目，请联系原作者。
原作者邮箱：tancawe@foxmail.com;&nbsp;
GitHub：https://github.com/chvin
感谢您为我发来的邮件，希望这些信息可以帮助到你。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr. X"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月7日(星期天) 晚上10:51
收件人:&nbsp;"chvin/react-tetris"<react-tetris@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[chvin/react-tetris] 请求上架到AppStore (#34)





 
作者你好，您这个项目太完美了，我想上架到AppStore可以吗？
 
我有苹果的开发者账号，想写一个简单的App，在App内用浏览器加载 https://chvin.github.io/react-tetris 这个页面。
  
会注明作者
 
不插入广告
 
免费

**Comment by chvin** [comment]
app astore 有一样类似界面的俄罗斯方块，预计审核不会通过，你可以尝试操作
