### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nihgwu** [chvin/react-tetris#4]
That's a wonderful project, what's the license? I'd like to port it to React Native if I could to follow your design

**Comment by chvin** [comment]
Apache Licene 2.0
react-tetris follow [经典方块游戏合集（掌上机经典）- 免费版](https://itunes.apple.com/cn/app/jing-dian-fang-kuai-you-xi/id963580334?mt=8) design on App Store.

**Comment by zolga** [comment]
Please add the LICENSE of this project to master.
