### ISSUE TITLE
无状态组件

### ISSUE THREAD

**Issue by xiaoyuhen** [chvin/react-tetris#5]
shouldcomponentupdate用的太多也不是太好，现在无状态组件可以使用```PureComponent```创建。

参考http://jamesknelson.com/should-i-use-shouldcomponentupdate/

**Comment by chvin** [comment]
性能聚焦在shouldComponentUpdate计算量和render的计算量谁更小，
react-tetris中全部写了shouldComponentUpdate，相对于全部不写，在手机上性能对比直观可见。

问题在于哪些应该不写，值得探究。游戏中用了Immutable，对shouldComponentUpdate的计算量是有更好的优化，没有文中说的`deepEquals `，所以暂时全部写了shouldComponentUpdate。如果有更好的方案、对比欢迎fork :)
