### ISSUE TITLE
No explicit license.

### ISSUE THREAD

**Issue by 226351** [chvin/react-tetris#51]
Hello Chvin,

I can see that the repository doesn't contain any license file.
READMEs also doesn't mention any licenses.

Could this be fixed, so everyone can clearly see how this repo may be used, please?

Kind regards

**Comment by aigouzz** [comment]
你的邮件我已收到，谢谢1

**Comment by chvin** [comment]
license: https://github.com/chvin/react-tetris/blob/master/package.json#L21
