### ISSUE TITLE
这不是一个实际的问题。

### ISSUE THREAD

**Issue by ryanabooth** [chvin/react-tetris#6]
我只是想说，这个项目是伟大的。 请原谅翻译。

**Comment by lildickme** [comment]
我只是想说，这个项目是伟大的。 请原谅翻译。????

**Comment by chvin** [comment]
I am not very good at English, the English version of the readme is also carried out through the Google translation, perhaps you can read the project and read the Notes in the English translation, and then pull requiret.

**Comment by Stoneleee** [comment]
I also want to say     Amazing !
