### ISSUE TITLE
Change name

### ISSUE THREAD

**Issue by napolux** [chvin/react-tetris#7]
Tetris is a copyrighted name. The company owning it defend it very aggressively. You are probably only days away from a "cease and desist" from their legal department.

**Comment by chvin** [comment]
谢谢提醒，据我所知，tetris是一个通用单词，我做的游戏就是tetris，github和appstore也有不少叫“tetris”相关的游戏。

**Comment by chvin** [comment]
Thank you remind, as far as I know, tetris is a common word, I do the game is tetris, github and appstore also has a lot of "tetris" related to the game.

**Comment by napolux** [comment]
AFAIK: http://gamedev.stackexchange.com/questions/16455/is-tetris-public-domain

**Comment by chvin** [comment]
Now that Tetris is a trademark, but I still will not change the project name, after all, tetris is the public are aware of the name, if tetris.com really will find me, is also an interesting thing.
